databases:
  - name: pedidosweb-db
    databaseName: pedidosweb
    plan: free

services:
  # Backend
  - type: web
    name: pedidos-back
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: pedidosweb-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: pedidosweb-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: pedidosweb-db
          property: database
      - key: JDBC_SSL_MODE
        value: "?sslmode=require"
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: pedidosweb-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: pedidosweb-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
    dockerContext: .
